version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=somepassword
  back:
    image: backend_poli
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    depends_on:
      - back
    image: front_poli
    environment:
      - REACT_APP_URL=http://localhost:3000
    ports:
      - "4000:5000"
