version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=somepassword

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    command: rails db:migrate
    command: rails server -b 0.0.0.0
    depends_on:
      - db
