require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gastos", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Gasto. As you add validations to Gasto, be sure to
  # adjust the attributes here as well.
  let(:user) { Usuario.create(nombre: 'Test', correo_electronico: 'test@email.com', password: 'secret') }
  let(:auth_token) do
    post '/autenticar', params: { correo_electronico: 'test@email.com', password: 'secret' }
    JSON.parse(response.body)['auth_token']
  end
  let(:valid_attributes) {
    { nombre: 'Compra laptop', monto: 3_000_000, fecha: Time.now, usuario: user }
  }

  let(:invalid_attributes) {
    { nombre: 'Compra laptop', monto: -5, fecha: Time.now, usuario: user }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # GastosController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    { Authorization: auth_token }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Gasto.create! valid_attributes
      get gastos_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gasto = Gasto.create! valid_attributes
      get gasto_url(gasto), as: :json, headers: valid_headers
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Gasto" do
        expect {
          post gastos_url,
               params: { gasto: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Gasto, :count).by(1)
      end

      it "renders a JSON response with the new gasto" do
        post gastos_url,
             params: { gasto: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Gasto" do
        expect {
          post gastos_url,
               params: { gasto: invalid_attributes }, as: :json
        }.to change(Gasto, :count).by(0)
      end

      it "renders a JSON response with errors for the new gasto" do
        post gastos_url,
             params: { gasto: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(/application\/json/)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gasto" do
        gasto = Gasto.create! valid_attributes
        patch gasto_url(gasto),
              params: { gasto: invalid_attributes }, headers: valid_headers, as: :json
        gasto.reload
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it "renders a JSON response with the gasto" do
        gasto = Gasto.create! valid_attributes
        patch gasto_url(gasto),
              params: { gasto: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(/application\/json/)
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the gasto" do
        gasto = Gasto.create! valid_attributes
        patch gasto_url(gasto),
              params: { gasto: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(/application\/json/)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gasto" do
      gasto = Gasto.create! valid_attributes
      expect {
        delete gasto_url(gasto), headers: valid_headers, as: :json
      }.to change(Gasto, :count).by(-1)
    end
  end
end
